{% set name = "pyinstrument" %}
{% set version = "4.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "3e509e879c853dbc5fdc1757f0cfdbf8bee899c80f53d504a7df28898f0fa8ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  skip: true  # [python_impl=='pypy']
  entry_points:
    - pyinstrument = pyinstrument.__main__:main

  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyinstrument
  requires:
    - pip
  commands:
    - pip check
    - pyinstrument --help

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A call stack profiler for Python. Inspired by Apple's Instruments.app
  dev_url: https://github.com/joerick/pyinstrument
  doc_url: https://pyinstrument.readthedocs.io/

extra:
  recipe-maintainers:
    - moorepants
    - asmeurer
    - matthiasdiener
