{% set name = "pyinstrument" %}
{% set version = "0.13.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "a0a645d69df12551214311fdf2e454c12b96cb0abc0f5dcc3067d8ef71713e02" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  entry_points:
    - pyinstrument = pyinstrument.__main__:main

  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pyinstrument

  commands:
    - pyinstrument --help

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD 3-Clause
  license_file: {{ RECIPE_DIR }}/LICENSE
  license_family: BSD
  summary: "A call stack profiler for Python. Inspired by Apple's Instruments.app"
  dev_url: https://github.com/joerick/pyinstrument

extra:
  recipe-maintainers:
    - pmlandwehr
